### ISSUE TITLE
EC2-stopped not working

### ISSUE THREAD

**Issue by satyajitkoijam** [aws-solutions/operations-conductor#1]
EC2-stopped task is not working/ stopping instance. I created task using SSM automation document and S3 folder as mention in document.

Please help and share SSM docs if anyone created, so that I can compare with mine.

**Comment by ericquinones** [comment]
Hi @satyajitkoijam 

It might help to check a couple of things before troubleshooting the SSM Automation Document itself:
* When creating the custom action, you will also need to create a CloudFormation template for the IAM Role that will be created to give Operations Conductor to stop the instance. Described in the _Create IAM Role Template_ section of [Appendix C](https://docs.aws.amazon.com/solutions/latest/operations-conductor/appendix-c.html)
* Are the resources (EC2 instances) tagged with the `target-tag` that you used when creating the task in the Operations Conductor UI? You can manually double check to make sure the correct tags are on the EC2 instances (double check the _Target Tag_ section of [Appendix A](https://docs.aws.amazon.com/solutions/latest/operations-conductor/appendix-a.html)) or you can check the CloudWatch logs for the Resource Selector lambda to make sure:
  * The lambda is being run (confirms your Operations Conductor task is set up and scheduled correctly) 
  * The resource selector is finding your EC2 instances. If you see that Resource Selector found 0 resources to act on, it's probably that the instances are not tagged.

If you've validated that the Operations Conductor task is created correctly and that Resource Selector is able to find your resources, then Operations Conductor should be executing your SSM Automation Document to stop the instances. The next step would be to have a look in the SSM console to see if there are any errors being reported in the execution of the automation document.
