### ISSUE TITLE
Compatibility Issue.

### ISSUE THREAD

**Issue by bibin-biju** [aws-solutions/operations-conductor#4]
Hello,

After implementation, trusted advisor shows that the source code uses a language which is deprecated.

Is there any plans to make this compatible?

**Comment by mobri2a** [comment]
Please share specifics on the error you are seeing. What language? A specific module or resource?

**Comment by gockle** [comment]
@bibin-biju The solutions new version v1.0.1 that is currently available [here](https://s3.amazonaws.com/solutions-reference/operations-conductor/latest/operations-conductor.template) will update the Nodejs versions to 14. Let me know that resolves the issue.

**Comment by bibin-biju** [comment]
@mobri2a @gockle 

Thanks for the update... No compatibility issues with the new template.
